# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 12345678
  host: localhost
  
development:
  <<: *default
  database: roomie_db